### PR TITLE
added exclusion of md5 files and print of file size alongside file names

### PR DESCRIPTION
**Pull request by friedrichknuth**

### CODE REVIEW

**Comment by tjcrone** [comment]
I like the exclusion of the MD5 files. Definitely necessary. However I think the function get_file_list needs to return a pure list of strings containing fully qualified URLs that can be used in all of the other functions. The get_stats() function does the size stuff. Any reason why you want file sizes to come out with the file names?

**Comment by tjcrone** [comment]
Let's change it so that the function returns two lists, file_list and file_sizes, rather than one list with the two interleaved.

**Comment by friedrichknuth** [comment]
how bout a dict? those are handy. if as a separate list, maybe a separate function entirely.

am looking to blend pycamhd with something like ooi_realtime_plotting to create an actively updating dashboard on berna of file sizes as they are written to the archive. might not need to be as instantaneous as what is going on in ooi_realtime_plotting. once a day to a static plot should suffice.

https://github.com/ooi-data-review/ooi-realtime-plotting

**Comment by tjcrone** [comment]
Yeah, I think that changing to a dict breaks too much of my code. If you want to have it output another list, we can do that.

**Pull request closed without merging**
